version: "3"
services:

  react:
    build:
      context: frontend
      dockerfile: reactfile
    restart: always
    ports: 
      - ${REACT_PORT}:5000

  server:
    build: server
    restart: always
    ports:
      - ${PORT}:${PORT}
  